#' A function to generate document term vectors from a variety of inputs.
#'
#' @param input A list of strings, term vectors, raw documents, or csv files you wish to turn into document term vectors.
#' @param data_type The type of data provided to the function.
#' @param data_directory Optional argument specifying where the data is stored.
#' @param tokenization_method Will eventually implement both an R-based and a Stanford CoreNLP based tokenization strategy. Currently not available.
#' @param output_type A string value indicating whether the resulting list object should be returned ("return"), saved to a file in the current working directory with name output_name.Rdata ("save"), of both ("save and return"). Defaults to "return".
#' @param output_name The file name we wish to give the output document term vector list object generated by this function if specifying a value of "save" or "return and save" for output_type. You do not need to provide the .Rdata extension as this is appended automatically. Defaults to NULL.
#' @param csv_separator Defaults to "," but can be set to "*backslash*t" for tab separated values.
#' @param csv_word_column  If you are providing one csv file per document, then you must specify the index of the column that contains the words. Defaults to NULL.
#' @param csv_count_column For memory efficiency, you may want to store only the counts of unique words in csv files. If your data include counts, then you must specify the index of the column that contains the counts. Defaults to NULL.
#' @param csv_header Logical indicating whether the csv files provided have a header. Defaults to FALSE.
#' @param keep_sequence Logical indicating whether document term vectors should be condensed and counts (FALSE) or whether the full sequence should be maintained for storage (TRUE). Defaults to FALSE as this can be a much more memory efficient representation.
#' @return A document term vector list.
#' @export
generate_document_term_vectors <- function(
    input,
    data_type = c("string","term vector","raw text","csv"),
    data_directory = NULL,
    tokenization_method = c("RegEx","CoreNLP"),
    output_type = c("return", "save", "return and save"),
    output_name = NULL,
    csv_separator = ",",
    csv_word_column = NULL,
    csv_count_column = NULL,
    csv_header = FALSE,
    keep_sequence = FALSE){

    # deal with default values
    if(length(data_type)> 1){
        data_type <- data_type[1]
    }
    if(length(tokenization_method)> 1){
        tokenization_method <- tokenization_method[1]
    }
    if(length(output_type)> 1){
        output_type <- output_type[1]
    }

    # get current working directory
    current_directory <- getwd()
    # now set the working directory if one was provided
    if(!is.null(data_directory)){
        setwd(data_directory)
    }

    # check to make sure an output name is provided if we are saving
    if(output_type != "return"){
        if(is.null(output_name)){
            stop("You must provide a valid output name if you wish to save output to disk. You do not need to provide the .Rdata extension as this is appended automatically.\n")
        }
    }

    # allocate list objects
    document_term_vector_list <- vector(mode= "list", length = length(input))
    document_term_count_list <- vector(mode= "list", length = length(input))

    #**********************#
    #****** CSV Data ******#
    #**********************#
    if(data_type == "csv"){

        # if csv_count_column is not NULL, then warn the user that we are not
        # keeping sequence
        if(!is.null(csv_count_column) &  keep_sequence){
            keep_sequence <- FALSE
            warning("You provided a csv_count_column so keep_sequence was set to FALSE. If you intended to keep sequence, then set csv_count_column = NULL.\n")
        }

        if(!keep_sequence & is.null(csv_count_column)){
            stop("You must provide a csv_count_column index if keep_sequence == FALSE.\n")
        }

        if(class(input) == "list"){
            input <- unlist(input)
        }

        if(keep_sequence){
            for(i in 1:length(input)){
                data <- readr::read_delim(file = input[i],
                                        delim = csv_separator,
                                        col_names = csv_header)
                document_term_vector_list[[i]] <- as.character(data[,csv_word_column])
            }

        }else{
            for(i in 1:length(input)){
                cat("Reading in file",i,"of",length(input),"\n")
                data <- readr::read_delim(file = input[i],
                                 delim = csv_separator,
                                 col_names = csv_header)
                vocab <- count_words(
                    document_term_vector_list = list(as.character(data[,csv_word_column])),
                    maximum_vocabulary_size = -1,
                    document_term_count_list = list(as.numeric(data[,csv_count_column])))
                document_term_vector_list[[i]] <- vocab$unique_words
                document_term_count_list[[i]] <- vocab$word_counts
            }

        }


    }

    # return everything
    if(output_type == "return"){
        if(keep_sequence){
            return(document_term_vector_list)
        }else{
            return_list <- list(
                document_term_vector_list = document_term_vector_list,
                document_term_count_list = document_term_count_list
                                )
            return(return_list)
        }
    }else if(output_type == "return"){
        if(keep_sequence){
            save(document_term_vector_list,
                 file = paste(output_name,".Rdata", sep = ""))
        }else{
            save(list = c("document_term_vector_list",
                          "document_term_count_list"),
                 file = paste(output_name,".Rdata", sep = ""))
        }
    }else{
        if(keep_sequence){
            return(document_term_vector_list)
            save(document_term_vector_list,
                 file = paste(output_name,".Rdata", sep = ""))
        }else{
            save(list = c("document_term_vector_list",
                          "document_term_count_list"),
                 file = paste(output_name,".Rdata", sep = ""))
            return_list <- list(
                document_term_vector_list = document_term_vector_list,
                document_term_count_list = document_term_count_list
            )
            return(return_list)
        }
    }
}
